Non- pkg-config ncurses support added.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1183,6 +1183,209 @@ fi;
 echo "#undef HAVE_NCURSES" >config/have_ncurses.h
 echo "hdefs[\"HAVE_NCURSES\"] = nil" >>configure.lua
 fi;
+if [ "${HAVE_NCURSES}" != "yes" ]
+ then
+$ECHO_N "checking for ncurses (http://www.gnu.org/software/ncurses)..."
+$ECHO_N "checking for ncurses (http://www.gnu.org/software/ncurses)..." >> config.log
+NCURSES_CFLAGS=""
+NCURSES_LIBS=""
+if [ "" != "" ]; then
+if [ -e  "/include/ncurses.h" ]; then
+NCURSES_CFLAGS="-I/include"
+NCURSES_LIBS="-L/lib -lncurses"
+fi;
+if [ -e  "/include/ncurses/ncurses.h" ]; then
+NCURSES_CFLAGS="-I/include"
+NCURSES_LIBS="-L/lib -lncurses"
+fi;
+else
+if [ -e  "/usr/local/include/ncurses.h" ]; then
+NCURSES_CFLAGS="-I/usr/local/include"
+NCURSES_LIBS="-L/usr/local/lib -lncurses"
+fi;
+if [ -e  "/usr/local/include/ncurses/ncurses.h" ]; then
+NCURSES_CFLAGS="-I/usr/local/include"
+NCURSES_LIBS="-L/usr/local/lib -lncurses"
+fi;
+if [ -e  "/usr/include/ncurses.h" ]; then
+NCURSES_CFLAGS="-I/usr/include"
+NCURSES_LIBS="-L/usr/lib -lncurses"
+fi;
+if [ -e  "/usr/include/ncurses/ncurses.h" ]; then
+NCURSES_CFLAGS="-I/usr/include"
+NCURSES_LIBS="-L/usr/lib -lncurses"
+fi;
+if [ -e  "/opt/local/include/ncurses.h" ]; then
+NCURSES_CFLAGS="-I/opt/local/include"
+NCURSES_LIBS="-L/opt/local/lib -lncurses"
+fi;
+if [ -e  "/opt/local/include/ncurses/ncurses.h" ]; then
+NCURSES_CFLAGS="-I/opt/local/include"
+NCURSES_LIBS="-L/opt/local/lib -lncurses"
+fi;
+if [ -e  "/opt/include/ncurses.h" ]; then
+NCURSES_CFLAGS="-I/opt/include"
+NCURSES_LIBS="-L/opt/lib -lncurses"
+fi;
+if [ -e  "/opt/include/ncurses/ncurses.h" ]; then
+NCURSES_CFLAGS="-I/opt/include"
+NCURSES_LIBS="-L/opt/lib -lncurses"
+fi;
+fi;
+if [ "${NCURSES_LIBS}" != "" ]; then
+echo "yes"
+echo "yes" >> config.log
+$ECHO_N "checking whether ncurses works..."
+$ECHO_N "checking whether ncurses works..." >> config.log
+MK_CACHED="No"
+MK_COMPILE_STATUS="OK"
+if [ "${cache}" != "" ]; then
+	if [ -e "${cache}/ctest-HAVE_NCURSES" ]; then
+		HAVE_NCURSES=`cat ${cache}/ctest-HAVE_NCURSES`
+		MK_COMPILE_STATUS=`cat ${cache}/ctest-status-HAVE_NCURSES`
+		MK_CACHED="Yes"
+	fi
+fi
+if [ "${MK_CACHED}" = "No" ]; then
+	cat << EOT > conftest.c
+#include <ncurses.h>
+
+int
+main(int argc, char *argv[])
+{
+	return (0);
+}
+
+EOT
+	echo "$CC $CFLAGS $TEST_CFLAGS ${NCURSES_CFLAGS} -o $testdir/conftest conftest.c ${NCURSES_LIBS}" >>config.log
+	$CC $CFLAGS $TEST_CFLAGS ${NCURSES_CFLAGS} -o $testdir/conftest conftest.c ${NCURSES_LIBS} 2>>config.log
+	if [ $? != 0 ]; then
+		echo "-> failed ($?)" >> config.log
+		MK_COMPILE_STATUS="FAIL($?)"
+	fi
+fi
+if [ "${MK_COMPILE_STATUS}" = "OK" ]; then
+echo "yes"
+echo "yes" >> config.log
+HAVE_NCURSES="yes"
+echo "#ifndef HAVE_NCURSES" > config/have_ncurses.h
+echo "#define HAVE_NCURSES \"$HAVE_NCURSES\"" >> config/have_ncurses.h
+echo "#endif" >> config/have_ncurses.h
+echo "hdefs[\"HAVE_NCURSES\"] = \"$HAVE_NCURSES\"" >>configure.lua
+else
+echo "no"
+echo "no" >> config.log
+HAVE_NCURSES="no"
+echo "#undef HAVE_NCURSES" >config/have_ncurses.h
+echo "hdefs[\"HAVE_NCURSES\"] = nil" >>configure.lua
+fi;
+if [ "${cache}" != "" ]; then
+	echo "$HAVE_NCURSES" > ${cache}/ctest-HAVE_NCURSES
+	echo $MK_COMPILE_STATUS > ${cache}/ctest-status-HAVE_NCURSES
+fi
+rm -f conftest.c $testdir/conftest$EXECSUFFIX
+if [ "${HAVE_NCURSES}" = "yes" ]; then
+echo "#ifndef NCURSES_CFLAGS" > config/ncurses_cflags.h
+echo "#define NCURSES_CFLAGS \"$NCURSES_CFLAGS\"" >> config/ncurses_cflags.h
+echo "#endif" >> config/ncurses_cflags.h
+echo "hdefs[\"NCURSES_CFLAGS\"] = \"$NCURSES_CFLAGS\"" >>configure.lua
+echo "#ifndef NCURSES_LIBS" > config/ncurses_libs.h
+echo "#define NCURSES_LIBS \"$NCURSES_LIBS\"" >> config/ncurses_libs.h
+echo "#endif" >> config/ncurses_libs.h
+echo "hdefs[\"NCURSES_LIBS\"] = \"$NCURSES_LIBS\"" >>configure.lua
+else
+echo "#undef NCURSES_CFLAGS" >config/ncurses_cflags.h
+echo "hdefs[\"NCURSES_CFLAGS\"] = nil" >>configure.lua
+NCURSES_CFLAGS=""
+echo "#undef NCURSES_LIBS" >config/ncurses_libs.h
+echo "hdefs[\"NCURSES_LIBS\"] = nil" >>configure.lua
+NCURSES_LIBS=""
+fi;
+MK_CACHED="No"
+MK_COMPILE_STATUS="OK"
+if [ "${cache}" != "" ]; then
+	if [ -e "${cache}/ctest-HAVE_NCURSESNP" ]; then
+		HAVE_NCURSESNP=`cat ${cache}/ctest-HAVE_NCURSESNP`
+		MK_COMPILE_STATUS=`cat ${cache}/ctest-status-HAVE_NCURSESNP`
+		MK_CACHED="Yes"
+	fi
+fi
+if [ "${MK_CACHED}" = "No" ]; then
+	cat << EOT > conftest.c
+#include <ncurses.h>
+
+int
+main(int argc, char *argv[])
+{
+	return (0);
+}
+
+EOT
+	echo "$CC $CFLAGS $TEST_CFLAGS ${NCURSES_CFLAGS} -o $testdir/conftest conftest.c ${NCURSES_LIBS}" >>config.log
+	$CC $CFLAGS $TEST_CFLAGS ${NCURSES_CFLAGS} -o $testdir/conftest conftest.c ${NCURSES_LIBS} 2>>config.log
+	if [ $? != 0 ]; then
+		echo "-> failed ($?)" >> config.log
+		MK_COMPILE_STATUS="FAIL($?)"
+	fi
+fi
+if [ "${MK_COMPILE_STATUS}" = "OK" ]; then
+echo "yes"
+echo "yes" >> config.log
+HAVE_NCURSESNP="yes"
+echo "#ifndef HAVE_NCURSESNP" > config/have_ncursesnp.h
+echo "#define HAVE_NCURSESNP \"$HAVE_NCURSESNP\"" >> config/have_ncursesnp.h
+echo "#endif" >> config/have_ncursesnp.h
+echo "hdefs[\"HAVE_NCURSESNP\"] = \"$HAVE_NCURSESNP\"" >>configure.lua
+else
+echo "no"
+echo "no" >> config.log
+HAVE_NCURSESNP="no"
+echo "#undef HAVE_NCURSESNP" >config/have_ncursesnp.h
+echo "hdefs[\"HAVE_NCURSESNP\"] = nil" >>configure.lua
+fi;
+if [ "${cache}" != "" ]; then
+	echo "$HAVE_NCURSESNP" > ${cache}/ctest-HAVE_NCURSESNP
+	echo $MK_COMPILE_STATUS > ${cache}/ctest-status-HAVE_NCURSESNP
+fi
+rm -f conftest.c $testdir/conftest$EXECSUFFIX
+if [ "${HAVE_NCURSESNP}" = "yes" ]; then
+echo "#ifndef NCURSES_CFLAGS" > config/ncurses_cflags.h
+echo "#define NCURSES_CFLAGS \"$NCURSES_CFLAGS\"" >> config/ncurses_cflags.h
+echo "#endif" >> config/ncurses_cflags.h
+echo "hdefs[\"NCURSES_CFLAGS\"] = \"$NCURSES_CFLAGS\"" >>configure.lua
+echo "#ifndef NCURSES_LIBS" > config/ncurses_libs.h
+echo "#define NCURSES_LIBS \"$NCURSES_LIBS\"" >> config/ncurses_libs.h
+echo "#endif" >> config/ncurses_libs.h
+echo "hdefs[\"NCURSES_LIBS\"] = \"$NCURSES_LIBS\"" >>configure.lua
+else
+echo "#undef NCURSES_CFLAGS" >config/ncurses_cflags.h
+echo "hdefs[\"NCURSES_CFLAGS\"] = nil" >>configure.lua
+NCURSES_CFLAGS=""
+echo "#undef NCURSES_LIBS" >config/ncurses_libs.h
+echo "hdefs[\"NCURSES_LIBS\"] = nil" >>configure.lua
+NCURSES_LIBS=""
+fi;
+else
+echo "no"
+echo "no" >> config.log
+echo "#undef HAVE_NCURSES" >config/have_ncurses.h
+echo "hdefs[\"HAVE_NCURSES\"] = nil" >>configure.lua
+echo "#undef NCURSES_CFLAGS" >config/ncurses_cflags.h
+echo "hdefs[\"NCURSES_CFLAGS\"] = nil" >>configure.lua
+echo "#undef NCURSES_LIBS" >config/ncurses_libs.h
+echo "hdefs[\"NCURSES_LIBS\"] = nil" >>configure.lua
+fi;
+if [ "${HAVE_NCURSESNP}" != "yes" ]; then
+echo "* "
+echo "* " >> config.log
+echo "* This software requires ncursesnp installed on your system."
+echo "* This software requires ncursesnp installed on your system." >> config.log
+echo "* "
+echo "* " >> config.log
+echo "configure failed!"
+exit 1
+fi;
+fi
 $ECHO_N "checking for POSIX threads..."
 $ECHO_N "checking for POSIX threads..." >> config.log
 if [ "" != "" ]; then
@@ -2644,6 +2847,8 @@ echo "LIBEXECDIR=$LIBEXECDIR" >>Makefile.config
 echo "mdefs[\"LIBEXECDIR\"] = \"$LIBEXECDIR\"" >>configure.lua
 echo "HAVE_NCURSES=$HAVE_NCURSES" >>Makefile.config
 echo "mdefs[\"HAVE_NCURSES\"] = \"$HAVE_NCURSES\"" >>configure.lua
+echo "HAVE_NCURSESNP=$HAVE_NCURSESNP" >>Makefile.config
+echo "mdefs[\"HAVE_NCURSESNP\"] = \"$HAVE_NCURSESNP\"" >>configure.lua
 echo "PTHREADS_XOPEN_LIBS=$PTHREADS_XOPEN_LIBS" >>Makefile.config
 echo "mdefs[\"PTHREADS_XOPEN_LIBS\"] = \"$PTHREADS_XOPEN_LIBS\"" >>configure.lua
 echo "DATADIR=$DATADIR" >>Makefile.config
